name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        # See https://github.com/xu-cheng/latex-action/issues/32#issuecomment-626086551 for xindy fix
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          latexmk_use_xelatex: true
          root_file: main.tex
          texlive_version: 2025

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TehranThesis
          path: main.pdf
